apiVersion: apps/v1
kind: Deployment
metadata:
  name: high-resource-deployment
  namespace: high-resource-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: high-resource-app
  template:
    metadata:
      labels:
        app: high-resource-app
    spec:
      containers:
      - name: high-resource-container
        image: nginx:latest
        resources:
          requests:
            cpu: "4"
            memory: "8Gi"
          limits:
            cpu: "8"
            memory: "16Gi"