apiVersion: v1
kind: Namespace
metadata:
  name: high-resource-namespace
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: high-resource-quota
  namespace: high-resource-namespace
spec:
  hard:
    requests.cpu: "16"
    requests.memory: "32Gi"
    limits.cpu: "32"
    limits.memory: "64Gi"